version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=change-me-in-production
    volumes:
      - ./backend:/app

  frontend:
    build: 
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules # важно: изолируем модули контейнера от Windows
    stdin_open: true
    tty: true
    depends_on:
      - backend